[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0e1629"
backgroundColor = "#1c2638"
secondaryBackgroundColor = "#1c2638"
textColor = "#b8c4ff"
font = "monospace"
