[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#3755c3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#0e1629"
textColor = "#b8c4ff"
font = "monospace"
