[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#3755c3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#1e40af"
textColor = "#00288e"
font = "monospace"
